### ISSUE TITLE
表記ゆれ

### ISSUE THREAD

**Issue by Mamonbo** [l1048576/tk-jogakuin#8]
主に [ characters.adoc ](https://github.com/l1048576/tk-jogakuin/blob/master/settings/characters.adoc)にて。
作者によって表記が揺れている模様。

箇条書きは句読点を使わないといわれているが、それなりに長いので句読点を打ちたくなる。
箇条書きやめた方がいい?

**Comment by lo48576** [comment]
それ悩んでたんだよねぇ……
私が複数文あると最後にも句点打ちたくなる性質なので単文でも打ってたけど。

どうせ本文じゃないし、セクションごとに統一されていれば(他人の設定を弄るのはそんなに頻繁じゃないだろうし)良いのではないかと思うが、どうだろう。

**Comment by lo48576** [comment]
進展なさそうだし本編には関係ないので、既にあるものに倣いつつ各自勝手にやりましょうということで、ここで細かいフォーマットは決めないことにします。
問題があるようであれば、このissueをreopenしてください。
